version: '2'

services:
  celery:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      TEST_BROKER: pyamqp://rabbit:5672
      TEST_BACKEND: redis://redis
    volumes:
      - ../celery:/celery/celery
      - ../celery:/usr/local/lib/python3.6/site-packages/celery
      - ../t:/celery/t
    depends_on:
      - rabbit
      - redis

  rabbit:
    image: rabbitmq

  redis:
    image: redis
