version: '2'

services:
  celery:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      TEST_BROKER: pyamqp://rabbit:5672
      TEST_BACKEND: redis://redis
      WORKER_LOGLEVEL: INFO
    volumes:
      - ../celery:/celery/celery
      - ../t:/celery/t
    depends_on:
      - rabbit
      - redis
      - dynamodb

  rabbit:
    image: rabbitmq

  redis:
    image: redis

  dynamodb:
    image: dwmkerr/dynamodb
