version: '2'

services:
  celery:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      TEST_BROKER: pyamqp://rabbit:5672
      TEST_BACKEND: redis://redis
      PYTHONUNBUFFERED: "yes"
      REDIS_HOST: redis
      WORKER_LOGLEVEL: INFO
    tty: true
    volumes:
      - ../celery:/home/someone/celery
      - ../t:/home/someone/t
    depends_on:
      - rabbit
      - redis
      - dynamodb

  rabbit:
    image: rabbitmq

  redis:
    image: redis

  dynamodb:
    image: dwmkerr/dynamodb
